#!/bin/bash -x
#
# /sbin/dev_scripts/configureUFW
# (c) 2012 Sam Caldwell.  iTextFor.com.  All Rights Reserved.
# This script will configure the UFW firewall service for a web server.
#
ufw reset

ufw enable

ufw logging low
echo "configuring rules."
ufw limit in from any to any port 22
ufw allow in from any to any port 80
ufw allow in from any to any port 443
ufw allow in from any to any port 123
ufw allow in from any to any port 53
ufw allow out from any to any port 80
ufw allow out from any to any port 443
ufw allow out from any to any port 53
ufw allow out from any to any port 123
ufw allow out from any to any port 22

ufw deny in from any to any 
ufw deny out from any to any