#!/bin/bash
#
# createPassword.sh
# (c) 2010 Sam Caldwell.  Public Domain.
#
if [ -z $1 ]; then
	STRING_LENGTH=8
else
	STRING_LENGTH=$1
fi
SEED_SIZE=$(($STRING_LENGTH*1024))
ALLOWED_CHARS="A-Za-z0-9\.\-\_"
echo $(head -c$SEED_SIZE /dev/urandom | tr -dc $ALLOWED_CHARS | head -c$STRING_LENGTH)
