#!/bin/bash
#
# makeBuildActive
# (c) 2012 Sam Caldwell.  Public Domain
# This script will make newBuild active by
# changing the symbolic link at $ApplicationRoot

[ -z $ApplicationRoot ] && echo "ApplicationRoot not set." && exit 1
[ -z $ApplicationConfigDir ] && echo "ApplicationConfigDir not set." && exit 1

echo "Checking for a new build..."
newBuildConfig="$ApplicationConfigDir/newBuild.conf"
[ ! -f $newBuildConfig ] && echo "No new build exists" && exit 2

newBuild="$ApplicationRoot/$(cat $newBuildConfig)"
[ -z $newBuild ] && echo "Error!  Malformed newBuild.conf file." && exit 3
[ ! -d $newBuild ] && echo "Build is configured, but cannot be found. Expected: $newBuild" && exit 9
echo "newBuild found: $newBuild"

echo " "
echo "Removing symLinkFile to any existing build..."
symLinkFile="${ApplicationRoot}/latest"
[ -L $symLinkFile ] && rm $symLinkFile && echo "done."
[ -L $symLinkFile ] && echo "Error! Failed to remove symLinkFile." && exit 8

echo " "
echo "Creating new symLinkFile for newBuild..."
ln -s ${newBuild} $symLinkFile && echo "done."
[ ! -L $symLinkFile ] && echo "Failed to create symLinkFile for $newBuild" && exit 4

echo " "
echo "Cleanup..."
lastBuildConfig="$ApplicationConfigDir/lastBuild.conf"
latestBuildConfig="$ApplicationConfigDir/latestBuild.conf"
[ -d $lastBuildConfig ] && rm $lastBuildConfig
[ -d $latestBuildConfig ] && mv $latestBuildConfig $lastBuildConfig && echo "Updated lastBuildConfig."
mv $newBuildConfig $latestBuildConfig && echo "Updated latestBuild.conf successfully."
echo "done."
echo " "
echo "CURRENT BUILD: $(cat $latestBuildConfig)"
echo "LAST BUILD: $(cat $lastBuildConfig)"
echo " "
echo "Please run pruneBuilds to eliminate any build older than $(cat $lastBuildConfig)."
echo "In the case of emergency, run revertLastBuild to restore the previous build."
exit 0

